### ISSUE TITLE
Can't get VSCode extension working...

### ISSUE THREAD

**Issue by semorrison** [morph-labs/rift#135]
I tried installing via the extensions menu, and then again from source.

With either, I end up at the same error message:
```
unexpected error: Command failed: /Users/scott/.morph/env/bin/rift
Traceback (most recent call last):
File "/Users/scott/.morph/env/bin/rift", line 5, in <module> from rift.server.core import main 
File "/Users/scott/.morph/rift/rift-engine/rift/server/core.py", line 12, in <module> from rift.llm.gpt4all_model import Gpt4AllModel, Gpt4AllSettings 
File "/Users/scott/.morph/rift/rift-engine/rift/llm/gpt4all_model.py", line 9, in <module> from gpt4all import GPT4All 
File "/Users/scott/.morph/env/lib/python3.10/site-packages/gpt4all/__init__.py", line 1, in <module> from .pyllmodel import LLModel # noqa File "/Users/scott/.morph/env/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 50, in <module> llmodel = load_llmodel_library() 
File "/Users/scott/.morph/env/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 46, in load_llmodel_library llmodel_lib = ctypes.CDLL(llmodel_dir) 
File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.fr...
```
(apologies for terrible formatting and the trunction, I'm copying and pasting from the VSCode pop-up).

**Comment by semorrison** [comment]
The only other clue I've found so far is that in the Terminal / Output / Extension Host log I see at the end:
```
2023-08-10 20:53:32.918 [info] ExtensionService#_doActivateExtension morph.rift-vscode, startup: false, activationEvent: 'onView:RiftChat'
2023-08-10 20:53:37.128 [error] {"message":"Git relative path not found."}
```

**Comment by jesse-michael-han** [comment]
Hello Scott! The first error message looks like a potential issue with the C bindings for llmodel.

I would recommend creating a fresh virtual environment following the manual installation section of the README. Also happy to hop on a call to debug! Maybe we can coordinate in the Discord thread?

**Comment by Anonym0us33** [comment]
```
 python -V
Python 3.10.7```
Python 3.10 or above is not found on your system. Please install it and try again. Ensure that python3.10 is available and try installing Rift manually: https://www.github.com/morph-labs/rift

**Comment by semorrison** [comment]
@Anonym0us33, that's not the problem here:
```
% python -V
Python 3.11.4
```

**Comment by semorrison** [comment]
The problem was with the C binding for GPT4All. @jesse-michael-han kindly helped me out with a branch `jesse/semorrison-patch` that removed GPT4All for now.
