### ISSUE TITLE
Error following the "Installation for development / testing" terminal instructions

### ISSUE THREAD

**Issue by darrenaddy** [morph-labs/rift#149]
The instructions are sparse, so maybe they assume that I have knowledge that I do not yet possess...
:P but...
I cloned the rift repository from my Windows user directory. (if that is the problem, where should I be in the Windows file system when I run that git clone command?)
I figured out the next step (not mentioned in the Terminal instructions):
`cd rift/editors/rift-vscode`
before running the bash reinstall.sh. However when I do, I get the following output:
`Uninstalling extension...
Uninstalling morph.rift-vscode...
                                 Extension 'morph.rift-vscode' was successfully uninstalled!
                                                                                            Running 'npm run clean'...
/usr/bin/env: ‘bash\r’: No such file or directory
Running npm i
/usr/bin/env: ‘bash\r’: No such file or directory
Creating VSIX package...
/usr/bin/env: ‘bash\r’: No such file or directory
Installing extension...
Installing extensions...
                        R [Error]: ENOENT: no such file or directory, open 'c:\Users\darrena.DENVERPLASTICS\rift\editors\rift-vscode\*.vsix'
                        at h (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:49:4145)
      at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:49:5498
                                                                                                        at C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\yauzl\index.js:34:21
                                                                              at FSReqCallback.oncomplete (node:fs:198:23) {
      type: undefined,
                        cause: [Error: ENOENT: no such file or directory, open 'c:\Users\darrena.DENVERPLASTICS\rift\editors\rift-vscode\*.vsix'] {
                               errno: -4058,
                                                code: 'ENOENT',
                                                                   syscall: 'open',
                                                                                       path: 'c:\\Users\\darrena.DENVERPLASTICS\\rift\\editors\\rift-vscode\\*.vsix'
                                              }
                                               }
                                                Failed Installing Extensions: file:///c%3A/Users/darrena.DENVERPLASTICS/rift/editors/rift-vscode/%2A.vsix`
                                              
Thanks for any assistance!

**Comment by darrenaddy** [comment]
I got it working on my MacBook Air, so not concerned with the Windows installation, attm.
Thx.
