### ISSUE TITLE
Automatic Install Fails On Mac

### ISSUE THREAD

**Issue by topcheese** [morph-labs/rift#161]
`unexpected error: Command failed: /Users/jimbo/.morph/env/bin/rift Traceback (most recent call last): File "/Users/jimbo/.morph/env/bin/rift", line 5, in <module> from rift.server.core import main File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/server/core.py", line 9, in <module> from rift.server.lsp import LspServer File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/server/lsp.py", line 11, in <module> from rift.agents import AGENT_REGISTRY, Agent, AgentParams, AgentRegistryResult File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/agents/__init__.py", line 1, in <module> from .abstract import * File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/agents/abstract.py", line 10, in <module> import rift.llm.openai_types as openai File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/llm/__init__.py", line 2, in <module> from .openai_client import OpenAIClient File "/Users/jimbo/.morph/env/lib/...`

I'm not trying to do a manual install.  Is this supposed to work on Monterey 12.6.7?

**Comment by jesse-michael-han** [comment]
hello! thanks for making this issue - could you report the full error traceback? we're aware of the install issues on OSX and are currently writing a fix, so it would be good to know if this issue would be covered by that.

**Comment by topcheese** [comment]
Didn't realize there was more.   I tried to use brew to install OpenSSL 1.1, but that didn't work.  Looks like I'll have to manually install it.
unexpected error: Command failed: /Users/jimbo/.morph/env/bin/rift
Traceback (most recent call last):
  File "/Users/jimbo/.morph/env/bin/rift", line 5, in <module>
    from rift.server.core import main
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/server/core.py", line 9, in <module>
    from rift.server.lsp import LspServer
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/server/lsp.py", line 11, in <module>
    from rift.agents import AGENT_REGISTRY, Agent, AgentParams, AgentRegistryResult
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/agents/__init__.py", line 1, in <module>
    from .abstract import *
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/agents/abstract.py", line 10, in <module>
    import rift.llm.openai_types as openai
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/llm/__init__.py", line 2, in <module>
    from .openai_client import OpenAIClient
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/rift/llm/openai_client.py", line 51, in <module>
    ENCODER = get_encoding("cl100k_base")
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/tiktoken/registry.py", line 56, in get_encoding
    _find_constructors()
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/tiktoken/registry.py", line 32, in _find_constructors
    mod = importlib.import_module(mod_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/tiktoken_ext/openai_public.py", line 1, in <module>
    from tiktoken.load import data_gym_to_mergeable_bpe_ranks, load_tiktoken_bpe
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/tiktoken/load.py", line 10, in <module>
    import requests
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/jimbo/.morph/env/lib/python3.9/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168

Try installing Rift manually: https://www.github.com/morph-labs/rift

**Comment by jesse-michael-han** [comment]
Hello! Some people have had luck trying `pip install --upgrade urllib3` to fix the OpenSSL bug.

**Comment by bohblue2** [comment]
> pip install --upgrade urllib3

Thanks

**Comment by awatson1978** [comment]
Got the following error on Mac during install also:
`None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.`

May want to include the following in the Readme and installation script:
- PyTorch
- TensorFlow
- Flax
