### ISSUE TITLE
PydanticImportError

### ISSUE THREAD

**Issue by 3pillardeveloper** [morph-labs/rift#34]
Issue: I am unable to run `rift.server.core` see the error below:

Windows 10 OS.

Python 3 installed.

I ran the following in a Powershell 5 terminal:

```ps1
PS C:\Users\REDACTED\source\repos\rift> python -m venv rift_env

PS C:\Users\REDACTED\source\repos\rift> .\rift_env\Scripts\Activate.ps1

(rift_env) PS C:\Users\REDACTED\source\repos\rift> pip install -e .\rift-engine

(rift_env) PS C:\Users\REDACTED\source\repos\rift> python --version
Python 3.11.3

(rift_env) PS C:\Users\REDACTED\source\repos\rift> python -m rift.server.core --port 7797
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\server\core.py", line 5, in <module>
    from rift.server.lsp import LspServer
  File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\server\lsp.py", line 9, in <module>
    from rift.llm.abstract import (
  File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\llm\__init__.py", line 1, in <module>
    from .openai_client import OpenAIClient
  File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\llm\openai_client.py", line 20, in <module>
    from pydantic import BaseModel, BaseSettings, SecretStr
  File "C:\Users\REDACTED\source\repos\rift\rift_env\Lib\site-packages\pydantic\__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\REDACTED\source\repos\rift\rift_env\Lib\site-packages\pydantic\_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0/u/import-error
```

Expected: it works.
Actual: error.

**Comment by wsepesi** [comment]
Solved (on mac m1) by doing:
`pip uninstall pydantic`
`pip install "pydantic==1.*"`

Looks like the `.toml` file defaults to the newest version (v2) and the code relies on the v1 syntax. Will open a PR tomorrow if this isn't resolved before then. cc @pranavmital

**Comment by cat-turner** [comment]
How can i fix this with pipenv??

**Comment by jesse-michael-han** [comment]
`pipenv shell`, then from the project directory do `cd rift-engine && pipenv install -e .`
