### ISSUE TITLE
validation error for OpenAIClient api_key

### ISSUE THREAD

**Issue by 3pillardeveloper** [morph-labs/rift#65]
# Discussion

The error mentions an API key - does this project depend on Open API? I thought the whole point was to have an offline AI model so as not to be spied upon.

# Tooling

![image](https://github.com/morph-labs/rift/assets/127785530/47219ec1-307f-4e7f-83ff-08422b6ae8b7)

# Steps

- Open a new text file in VSCodium (open source VS-Code)
- Enter the prompt: `implement fizz-buzz in Python 3.`.
- Run the latest `master` Rift source code with `python -m rift.server.core --port 7797`:

```ps1
    [12:16:58] INFO     starting rift server on 7797                                                                                core.py:150
           INFO     listening with LSP protool on ('127.0.0.1', 7797)                                                            core.py:95
[12:27:43] INFO     <LspServer 1> transport closed gracefully: end of stream                                                 jsonrpc.py:541
           INFO     exiting serve_forever loop                                                                               jsonrpc.py:569
           INFO     <LspServer 1> entered shutdown state                                                                     jsonrpc.py:584
           INFO     initializing LSP server <LspServer 2>                                                                      server.py:47
           INFO     client initialized.                                                                                        server.py:55
[12:27:53] INFO     <LspServer 2> recieved model config chatModel='openai:gpt-3.5-turbo' completionsModel='openai:gpt-3.5-turbo' lsp.py:249
                    openaiKey=None
           ERROR    <LspServer 2> request morph/run_chat:1 unhandled ValidationError:                                        jsonrpc.py:648
                    1 validation error for OpenAIClient
                    api_key
                      field required (type=value_error.missing)
                    This is likely caused by a bug in the morph/run_chat method handler.
                    Traceback (most recent call last):
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\rpc\jsonrpc.py", line 633, in
                    _on_request
                        result = await self._on_request_core(req)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\rpc\jsonrpc.py", line 715, in
                    _on_request_core
                        result = await self.dispatcher.dispatch(req.method, params)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\rpc\jsonrpc.py", line 246, in
                    dispatch
                        result = await result
                                 ^^^^^^^^^^^^
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\server\lsp.py", line 339, in
                    on_run_chat
                        chat = await self.ensure_chat_model()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\server\lsp.py", line 315, in
                    ensure_chat_model
                        await self.get_config()
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\server\lsp.py", line 252, in
                    get_config
                        self.completions_model = config.create_completions()
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\llm\create.py", line 29, in
                    create_completions
                        return create_client(self.completionsModel, self.openaiKey)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\llm\create.py", line 56, in
                    create_client
                        client = create_client_core(config, openai_api_key)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "C:\Users\REDACTED\source\repos\rift\rift-engine\rift\llm\create.py", line 88, in
                    create_client_core
                        return OpenAIClient.parse_obj(kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
                      File "pydantic\env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
                      File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
                    pydantic.error_wrappers.ValidationError: 1 validation error for OpenAIClient
                    api_key
                      field required (type=value_error.missing)
```

**Comment by jesse-michael-han** [comment]
We support the `ggml-replit-code-v1-3b` model and others in the `gpt4all` toolchain out of the box. If you search for "RIft" in the VSCode settings you'll see some dropdown menus where you can specify the backend.
