### ISSUE TITLE
Error when running server in windows with Python 3.10.11

### ISSUE THREAD

**Issue by lutfi-haslab** [morph-labs/rift#8]
Hello, first of all this is really great, congratulations.
I was exited and want to try it in my machine, however i got error when running
```bash
 python -m rift.server.core --port 7797
```

the error message:
```bash
$ python -m rift.server.core --port 7797
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\rift\rift-engine\rift\server\core.py", line 5, in <module>
    from rift.server.lsp import LspServer
  File "E:\rift\rift-engine\rift\server\lsp.py", line 5, in <module>
    from miniscutil.lsp import LspServer as BaseLspServer, rpc_method
  File "C:\Users\prifalab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\miniscutil\__init__.py", line 7, in <module>
    from .misc import (
  File "C:\Users\prifalab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\miniscutil\misc.py", line 25, in <module>
    from typing_extensions import deprecated
ImportError: cannot import name 'deprecated' from 'typing_extensions' (C:\Users\prifalab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\typing_extensions.py)
```

Do i miss something?
thank you

**Comment by alex1234562** [comment]
python3 -m rift.server.core --port 7797

**Comment by lutfi-haslab** [comment]
Ok, it is finally works
- uninstalled python
- install latest python 3.11.4

**Comment by EdAyers** [comment]
I've removed the needless import of deprecated so this should be fixed now
